//
// Created by Olcay Taner YILDIZ on 22.03.2023.
//

#ifndef GRAPH_PUZZLE_GAME_KAANBUYUKKIVANC_DATASTRUCTURES_CPP_TOKENTYPE_H
#define GRAPH_PUZZLE_GAME_KAANBUYUKKIVANC_DATASTRUCTURES_CPP_TOKENTYPE_H

enum TokenType{
    OPERAND, OPERATOR
};

#endif //DATASTRUCTURES_CPP_TOKENTYPE_H
